# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qEewIxG5KNEUrbMPtS4Wh7kCcv9h4_N6

Task no 1
"""

import numpy as np

sensor_data = np.array([
    [12, 15, 14, 10, 13],
    [20, 22, 19, 18, 21],
    [30, 28, 27, 29, 31],
    [25, 24, 26, 23, 22]
])

avg_machine = np.mean(sensor_data, axis=1)

max_time = np.max(sensor_data, axis=0)

normalized = sensor_data / max_time

machines_gt_20 = np.where(avg_machine > 20)

reshaped = sensor_data.reshape(2, 10)

print(avg_machine)
print(max_time)
print(normalized)
print(machines_gt_20)
print(reshaped)

"""Task no 2"""

import numpy as np

A = np.random.randint(1, 51, (3, 3))
B = np.random.randint(1, 51, (3, 3))

mat_mul = A @ B

elem_mul = A * B

greater_100 = mat_mul[mat_mul > 100]

A[A < 10] = 0
B[B < 10] = 0

stacked = np.vstack((A, B))

print(A)
print(B)
print(mat_mul)
print(elem_mul)
print(greater_100)
print(stacked)

"""Task no 3"""

import pandas as pd

sales_data = {
    "OrderID": [101, 102, 103, 104, 105, 106],
    "Customer": ["Ali", "Sara", "Ahmed", "Ali", "Zain", "Sara"],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Category": ["Electronics", "Clothing", "Electronics", "Groceries", "Clothing", "Electronics"],
    "Amount": [12000, 3500, None, 2400, 5200, 15000]
}

df = pd.DataFrame(sales_data)

print(df.head(3))

print(df.isnull())

median_val = df["Amount"].median()

df["Amount"] = df["Amount"].fillna(median_val)

df["Amount"] = df["Amount"].astype(int)

df.to_csv("cleaned_data.csv", index=False)

print(df)

"""Task no 4"""

df["HighValue"] = df["Amount"] > 10000

karachi_orders = df[df["City"] == "Karachi"]

electronics_high = df[(df["Category"] == "Electronics") & (df["Amount"] > 10000)]

sorted_df = df.sort_values(by="Amount", ascending=False)

top_customers = df.groupby("Customer")["Amount"].sum().sort_values(ascending=False).head(2)

print(karachi_orders)
print(electronics_high)
print(sorted_df)
print(top_customers)

"""Task no 5"""

total_revenue_city = df.groupby("City")["Amount"].sum()

avg_category = df.groupby("Category")["Amount"].mean()

unique_customers = df.groupby("City")["Customer"].nunique()

pivot = pd.pivot_table(df, values="Amount", index="City", columns="Category", aggfunc="sum")

reset_df = total_revenue_city.reset_index()

print(total_revenue_city)
print(avg_category)
print(unique_customers)
print(pivot)
print(reset_df)